# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: serverless-app

provider:
  name: aws
  runtime: python3.8

  iam:
      role:
        statements:
          - Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Resource: 'arn:aws:dynamodb:us-east-1:*:*'

functions:
  post_create:
    handler: article/handler.create
    events:
      - http:
          path: article/create
          method: post
  post_get:
    handler: article/handler.get
    events:
      - http:
          path: article/get
          method: get
  post_all:
    handler: article/handler.all
    events:
      - http:
          path: article/all
          method: get
  post_update:
    handler: article/handler.update
    events:
      - http:
          path: article/update
          method: put
  post_delete:
    handler: article/handler.delete
    events:
      - http:
          path: article/delete
          method: delete

resources: 
    Resources:
      articleTable: 
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: article
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: N
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
  
#plugins:
#- serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux